# Generated by Django 3.2.9 on 2021-11-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='acting_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acting_person', to='leave.person'),
        ),
        migrations.AddField(
            model_name='application',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='end_date',
            field=models.DateTimeField(default='2021-10-21'),
        ),
        migrations.AddField(
            model_name='application',
            name='hasClasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='reschedules_date',
            field=models.DateTimeField(blank=True, default='2021-10-21'),
        ),
        migrations.AddField(
            model_name='application',
            name='start_date',
            field=models.DateTimeField(default='2021-10-21'),
        ),
        migrations.AddField(
            model_name='person',
            name='leave_count',
            field=models.IntegerField(default=22),
        ),
    ]
