# Generated by Django 3.2.9 on 2021-11-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20211120_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='reschedules_date',
            new_name='rescheduled_date',
        ),
    ]
