# Generated by Django 3.2.9 on 2021-11-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20211121_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
    ]
