# Generated by Django 3.2.9 on 2021-11-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20211121_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='acting_person',
        ),
        migrations.RemoveField(
            model_name='application',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applications', to='leave.Application'),
        ),
    ]
