# Generated by Django 3.2.9 on 2021-11-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20211121_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='applications',
        ),
        migrations.AddField(
            model_name='application',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leave.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='start_date',
            field=models.DateField(),
        ),
    ]
