# Generated by Django 3.2.9 on 2021-11-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20211121_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['start_date', 'end_date']},
        ),
        migrations.AddField(
            model_name='application',
            name='up_next',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='up_next', to='leave.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('DR', 'Director'), ('DOAA', 'Dean of Academic Affairs'), ('DOFA', 'Dean of Faculty Affairs'), ('DOSA', 'Dean of Student Affairs'), ('HOD', 'Head of Department'), ('F', 'Faculty'), ('VF', 'Visiting Faculty')], default='F', max_length=5),
        ),
    ]
