# Generated by Django 3.2.9 on 2021-11-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20211123_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rescheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
