# Generated by Django 3.2.9 on 2021-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_alter_application_rescheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rescheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
