# Generated by Django 3.2.9 on 2021-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_alter_application_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='office_no',
            field=models.IntegerField(default='0000'),
        ),
    ]
