# Generated by Django 3.2.9 on 2021-12-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0018_alter_person_office_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
