# Generated by Django 3.2.9 on 2021-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical and Mechatronics Engineering'), ('HSS', 'Humanities and Social Sciences'), ('MH', 'Mathematics'), ('PH', 'Physics'), ('NTS', 'Non Teaching Staff')], default='CSE', max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('DR', 'Director'), ('DOAA', 'Dean of Academic Affairs'), ('DOFA', 'Dean of Faculty Affairs'), ('DOSA', 'Dean of Student Affairs'), ('HOD', 'Head of Department'), ('F', 'Faculty'), ('VF', 'Visiting Faculty'), ('RG', 'Registrar'), ('HOS', 'Head of Staff'), ('S', 'Staff')], default='F', max_length=5),
        ),
    ]
