# Generated by Django 3.2.9 on 2022-01-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_auto_20211228_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='faculty_id',
            field=models.CharField(default='0', max_length=10, unique=True),
        ),
    ]
