# Generated by Django 4.1.2 on 2022-10-29 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0021_alter_person_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='leave_count',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)]),
        ),
    ]
